In [1]:
import json
import requests
import pandas as pd

# insert your API key here
API_KEY = '21cdh0TAgTljZ1HdvVpmbLxuoo2'

#metrics_df = pd.DataFrame()

# make API requests
price = requests.get('https://api.glassnode.com/v1/metrics/market/price_usd_close',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

asopr = requests.get('https://api.glassnode.com/v1/metrics/indicators/sopr_adjusted',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

puell = requests.get('https://api.glassnode.com/v1/metrics/indicators/puell_multiple',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

exchange_flow = requests.get('https://api.glassnode.com/v1/metrics/transactions/transfers_volume_exchanges_net',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

diff_comp = requests.get('https://api.glassnode.com/v1/metrics/indicators/difficulty_ribbon_compression',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

mvrvz = requests.get('https://api.glassnode.com/v1/metrics/market/mvrv_z_score',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

nonzero_addy = requests.get('https://api.glassnode.com/v1/metrics/addresses/non_zero_count',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

utxo_percent_profit = requests.get('https://api.glassnode.com/v1/metrics/blockchain/utxo_profit_relative',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

nvt = requests.get('https://api.glassnode.com/v1/metrics/indicators/nvts',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

nupl = requests.get('https://api.glassnode.com/v1/metrics/indicators/net_unrealized_profit_loss',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

stablecoin_supply = requests.get('https://api.glassnode.com/v1/metrics/indicators/ssr_oscillator',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

rhodl = requests.get('https://api.glassnode.com/v1/metrics/indicators/rhodl_ratio',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

cvdd = requests.get('https://api.glassnode.com/v1/metrics/indicators/cvdd',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

rpv = requests.get('https://api.glassnode.com/v1/metrics/indicators/realized_profits_to_value_ratio',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

svab = requests.get('https://api.glassnode.com/v1/metrics/indicators/svab',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

In [ ]:
display(price.json())

In [2]:
# convert to pandas dataframe
price_df = pd.read_json(price.text, convert_dates=['t'])
price_df = price_df.rename(columns={'t': 'date', 'v': 'price'})
price_df = price_df.set_index('date')

asopr_df = pd.read_json(asopr.text, convert_dates=['t'])
asopr_df = asopr_df.rename(columns={'t': 'date', 'v': 'asopr'})
asopr_df = asopr_df.set_index('date')

puell_df = pd.read_json(puell.text, convert_dates=['t'])
puell_df = puell_df.rename(columns={'t': 'date', 'v': 'puell'})
puell_df = puell_df.set_index('date')

exchange_flow_df = pd.read_json(exchange_flow.text, convert_dates=['t'])
exchange_flow_df = exchange_flow_df.rename(columns={'t': 'date', 'v':'exchange_netflow'})
exchange_flow_df = exchange_flow_df.set_index('date')

diff_comp_df = pd.read_json(diff_comp.text, convert_dates=['t'])
diff_comp_df = diff_comp_df.rename(columns={'t': 'date', 'v': 'difficulty_compression_band'})
diff_comp_df = diff_comp_df.set_index('date')

mvrvz_df = pd.read_json(mvrvz.text, convert_dates=['t'])
mvrvz_df = mvrvz_df.rename(columns={'t': 'date', 'v': 'mvrvz'})
mvrvz_df = mvrvz_df.set_index('date')

                   price
date
2010-07-17      0.049510
2010-07-18      0.085840
2010-07-19      0.080800
2010-07-20      0.074733
2010-07-21      0.079210
...                  ...
2021-11-26  53761.701725
2021-11-27  54542.063604
2021-11-28  57201.708015
2021-11-29  57816.065292
2021-11-30  57158.880891

[4155 rows x 1 columns]

In [3]:
# Add each metric to the main dataframe

metrics_df = price_df
metrics_df['a_sopr'] = asopr_df['asopr']
metrics_df['puell_multiple'] = puell_df['puell']
metrics_df['exchange_netflow'] = exchange_flow_df['exchange_netflow']
metrics_df['difficulty_compression_band'] = diff_comp_df['difficulty_compression_band']
metrics_df['mvrv_z_score'] = mvrvz_df['mvrvz']
metrics_df

,price,a_sopr,puell_multiple,exchange_netflow,difficulty_compression_band,mvrv_z_score
date,,,,,,
2010-07-17,0.049510,1.000000,NaN,NaN,0.548957,-6.060000e-13
2010-07-18,0.085840,1.198127,NaN,NaN,0.608607,2.518053e+00
2010-07-19,0.080800,1.378311,NaN,NaN,0.652693,2.097027e+00
2010-07-20,0.074733,NaN,NaN,NaN,0.686378,1.651545e+00
2010-07-21,0.079210,NaN,NaN,NaN,0.713103,1.927019e+00
...,...,...,...,...,...,...
2021-11-26,53761.701725,NaN,NaN,NaN,NaN,NaN
2021-11-27,54542.063604,NaN,NaN,NaN,NaN,NaN
2021-11-28,57201.708015,NaN,NaN,NaN,NaN,NaN
2021-11-29,57816.065292,NaN,NaN,NaN,NaN,NaN
2021-11-30,57213.934986,NaN,NaN,NaN,NaN,NaN