In [51]:
import json
import requests
import pandas as pd

# insert your API key here
API_KEY = '21cdh0TAgTljZ1HdvVpmbLxuoo2'

metrics_df = pd.DataFrame()

# make API requests

asopr = requests.get('https://api.glassnode.com/v1/metrics/indicators/sopr_adjusted',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

puell = requests.get('https://api.glassnode.com/v1/metrics/indicators/puell_multiple',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

exchange_flow = requests.get('https://api.glassnode.com/v1/metrics/indicators/transfers_volume_exchanges_net',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

difficulty_compression = requests.get('https://api.glassnode.com/v1/metrics/indicators/difficulty_ribbon_compression',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

mvrvz = requests.get('https://api.glassnode.com/v1/metrics/indicators/mvrv_z_score',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

price = requests.get('https://api.glassnode.com/v1/metrics/indicators/price_usd_close',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

nonzero_addy = requests.get('https://api.glassnode.com/v1/metrics/indicators/non_zero_count',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

utxo_percent_profit = requests.get('https://api.glassnode.com/v1/metrics/indicators/utxo_profit_relative',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

nvt = requests.get('https://api.glassnode.com/v1/metrics/indicators/nvts',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

nupl = requests.get('https://api.glassnode.com/v1/metrics/indicators/net_unrealized_profit_loss',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

stablecoin_supply = requests.get('https://api.glassnode.com/v1/metrics/indicators/ssr_oscillator',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

rhodl = requests.get('https://api.glassnode.com/v1/metrics/indicators/rhodl_ratio',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

cvdd = requests.get('https://api.glassnode.com/v1/metrics/indicators/cvdd',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

rpv = requests.get('https://api.glassnode.com/v1/metrics/indicators/realized_profits_to_value_ratio',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

svab = requests.get('https://api.glassnode.com/v1/metrics/indicators/svab',
    params={'a': 'BTC', 'api_key': API_KEY, 'i': '24h', 'f': 'JSON'})

In [56]:
responses = [asopr, puell, exchange_flow, difficulty_compression, mvrvz, price, nonzero_addy, utxo_percent_profit, nvt, nupl, stablecoin_supply, rhodl, cvdd, rpv, svab]

responses

[<Response [200]>,
 <Response [200]>,
 <Response [404]>,
 <Response [200]>,
 <Response [404]>,
 <Response [404]>,
 <Response [404]>,
 <Response [404]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>,
 <Response [200]>]

In [ ]:
# convert to pandas dataframe

asopr_df = pd.read_json(asopr.text, convert_dates=['t'])
asopr_df = asopr_df.rename(columns={'t': 'date', 'v': 'asopr'})
asopr_df = asopr_df.set_index('date')

In [52]:
puell_df = pd.read_json(puell.text, convert_dates=['t'])
puell_df = puell_df.rename(columns={'t': 'date', 'v': 'puell'})
puell_df = puell_df.set_index('date')

               puell
date
2011-07-16  3.656330
2011-07-17  3.830945
2011-07-18  3.691357
2011-07-19  3.244558
2011-07-20  3.366804
...              ...
2020-11-25  1.513527
2020-11-26  1.335441
2020-11-27  1.342383
2020-11-28  1.363777
2020-11-29  1.379278

[3425 rows x 1 columns]

In [54]:
metrics_df = asopr_df
metrics_df['puell'] = puell_df['puell']
metrics_df

               asopr     puell
date
2010-07-17  1.000000       NaN
2010-07-18  1.198127       NaN
2010-07-19  1.378311       NaN
2010-07-20       NaN       NaN
2010-07-21       NaN       NaN
...              ...       ...
2020-11-25  1.052791  1.513527
2020-11-26  1.038922  1.335441
2020-11-27  1.029315  1.342383
2020-11-28  1.026012  1.363777
2020-11-29  1.037644  1.379278

[3789 rows x 2 columns]